# email_notifier.py

import os
import re
import glob
import logging
import smtplib
from typing import List, Optional, Dict
from datetime import datetime, timedelta
from pathlib import Path
import zipfile

import pandas as pd

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from email.utils import formataddr

__all__ = ["EnhancedEmailSystem", "EmailNotifier"]


class EnhancedEmailSystem:
    """Email system that assembles a reports+invoices ZIP and sends it with a professional HTML body."""

    def __init__(self, smtp_server=None, smtp_port=None, username=None, password=None):
        # Prefer SMTP_* secrets; fallback to EMAIL_*
        self.smtp_server = smtp_server or os.getenv("SMTP_HOST") or os.getenv("SMTP_SERVER", "smtp.office365.com")
        self.smtp_port = int(smtp_port or os.getenv("SMTP_PORT", "587"))
        self.username = username or os.getenv("SMTP_USER") or os.getenv("EMAIL_USERNAME")
        self.password = password or os.getenv("SMTP_PASS") or os.getenv("EMAIL_PASSWORD")

        # Recipients configuration with validation
        recipients_str = (
            os.getenv("AP_TEAM_EMAIL_LIST")
            or os.getenv("EMAIL_RECIPIENTS")
            or os.getenv("TEAM_EMAIL_LIST")
            or ""
        )
        self.default_recipients = self._validate_email_list(recipients_str) if recipients_str else []

        # Attachment size cap (MB) to keep emails deliverable
        self.max_zip_bytes = int(os.getenv("EMAIL_MAX_ZIP_MB", "24")) * 1024 * 1024

        # Logger
        self.logger = logging.getLogger(__name__)

    # ---------- HTML body ----------

    def create_professional_html_template(self, validation_data: dict, deadline_date: datetime) -> str:
        critical_count = validation_data.get("failed", 0)
        warning_count = validation_data.get("warnings", 0)
        passed_count = validation_data.get("passed", 0)
        total_count = critical_count + warning_count + passed_count
        pass_rate = (passed_count / total_count * 100) if total_count > 0 else 0

        critical_amount = "₹1,50,000"
        warning_amount = "₹1,40,000"

        return f"""<!DOCTYPE html>
<html>
  <body style="font-family: Arial, sans-serif; color:#111;">
    <h2>🏢 KOENIG INVOICE VALIDATION REPORT</h2>
    <p>Automated Processing Summary - {datetime.now().strftime('%B %d, %Y')}</p>

    <h3>📊 EXECUTIVE SUMMARY</h3>
    <p>Processing Rate: <b>{pass_rate:.1f}%</b> ({passed_count}/{total_count} invoices processed successfully)</p>

    <table border="1" cellpadding="6" cellspacing="0">
      <tr><th>Status</th><th>Count</th><th>Financial Impact</th></tr>
      <tr><td>🚨 CRITICAL ISSUES</td><td>{critical_count}</td><td>{critical_amount}</td></tr>
      <tr><td>⚠️ WARNING ITEMS</td><td>{warning_count}</td><td>{warning_amount}</td></tr>
      <tr><td>✅ SUCCESSFULLY PROCESSED</td><td>{passed_count}</td><td>Ready for Payment</td></tr>
    </table>

    <h3>🚨 IMMEDIATE ACTION REQUIRED</h3>
    <p>Response Deadline: <b>{deadline_date.strftime('%B %d, %Y at %I:%M %p IST')}</b></p>

    <h3>📎 ATTACHMENTS INCLUDED</h3>
    <ul>
      <li>Validation Report (formatted as requested)</li>
      <li>Real invoice files (as many as fit within email size limits)</li>
      <li>Other run reports</li>
    </ul>

    <hr/>
    <p>Koenig Solutions Pvt. Ltd. | Generated by Invoice Management System</p>
    <p style="color:#555;">This is an automated report containing confidential information</p>
  </body>
</html>"""

    # ---------- Helpers ----------

    def _validate_email_list(self, recipients_str: str) -> List[str]:
        """Validate and clean email recipient list (comma/semicolon separated)"""
        email_pattern = re.compile(r"^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$")
        emails: List[str] = []
        for raw in recipients_str.replace(";", ",").split(","):
            email = raw.strip()
            if not email:
                continue
            if email_pattern.match(email):
                emails.append(email)
            else:
                self.logger.warning(f"Invalid email format ignored: {email}")
        return emails

    def _today_dir_guess(self) -> Optional[Path]:
        # Looks like data/YYYY-MM-DD is used. Fall back to newest folder under data/.
        data_root = Path("data")
        if not data_root.exists():
            return None
        # Prefer today's IST date folder if present
        today = datetime.now().strftime("%Y-%m-%d")
        td = data_root / today
        if td.exists():
            return td
        # Else newest by mtime
        dated = [p for p in data_root.iterdir() if p.is_dir()]
        return max(dated, key=lambda p: p.stat().st_mtime) if dated else None

    def _read_latest_rms_table(self) -> Optional[pd.DataFrame]:
        """
        Try to load the tab-separated RMS export (invoice_download.xls) as DataFrame of strings.
        """
        ddir = self._today_dir_guess()
        if not ddir:
            return None
        # Prefer invoice_download.xls under today dir
        tsv_path = ddir / "invoice_download.xls"
        if tsv_path.exists():
            try:
                df = pd.read_csv(tsv_path, sep="\t", dtype=str, engine="python")
                return df
            except Exception as e:
                self.logger.warning(f"Could not read TSV from {tsv_path}: {e}")
        # Fallback: try any such file under data/*/
        candidates = glob.glob("data/*/invoice_download.xls")
        if candidates:
            latest = max(candidates, key=os.path.getctime)
            try:
                return pd.read_csv(latest, sep="\t", dtype=str, engine="python")
            except Exception as e:
                self.logger.warning(f"Could not read TSV from {latest}: {e}")
        return None

    def _read_latest_detailed_validation(self) -> Optional[pd.DataFrame]:
        """
        Try to load the detailed validation output to pull Validation_Status / Issue_Details.
        """
        paths = glob.glob("data/invoice_validation_detailed_*.xlsx") or []
        if not paths:
            return None
        latest = max(paths, key=os.path.getctime)
        try:
            return pd.read_excel(latest)
        except Exception as e:
            self.logger.warning(f"Could not read detailed validation workbook: {latest}: {e}")
            return None

    def _safe_get(self, row: Dict[str, str], names: List[str]) -> Optional[str]:
        """
        Case-insensitive lookup from a row-dict (keys are original df columns).
        Returns first non-empty value among candidates.
        """
        lower_map = {k.lower(): k for k in row.keys()}
        for name in names:
            key = lower_map.get(name.lower())
            if key:
                v = row.get(key)
                if pd.notna(v) and str(v).strip() != "":
                    return str(v).strip()
        return None

    def _num(self, x) -> float:
        try:
            s = str(x).replace(",", "").strip()
            return float(s) if s not in ("", "None", "nan") else 0.0
        except Exception:
            return 0.0

    # ---------- Report builder (requested format) ----------

    def build_formatted_validation_report(self) -> Optional[str]:
        """
        Build Excel at data/validation_report_formatted_YYYY-MM-DD.xlsx
        with the requested column order, using best-effort field mapping from RMS export
        plus (if available) detailed validation outputs.
        """
        df_rms = self._read_latest_rms_table()
        if df_rms is None or df_rms.empty:
            self.logger.error("No RMS table found to build formatted validation report.")
            return None

        # Map detailed validation by invoice number (best effort)
        detail = self._read_latest_detailed_validation()
        validation_lookup = {}
        if detail is not None and not detail.empty:
            # Find likely columns
            cols_lower = {c.lower(): c for c in detail.columns}
            inv_col = cols_lower.get("invoice number") or cols_lower.get("invoice_number") or cols_lower.get("purchaseinvno") or None
            status_col = cols_lower.get("validation status") or cols_lower.get("validation_status") or cols_lower.get("validation result") or cols_lower.get("validation_result")
            issues_col = cols_lower.get("issues_found") or cols_lower.get("error details") or cols_lower.get("error_details")
            # Build lookup: invoice_number -> (status, issues, details)
            if inv_col is not None:
                for _, r in detail.iterrows():
                    key = str(r.get(inv_col, "")).strip()
                    if key:
                        validation_lookup[key] = {
                            "Validation_Status": str(r.get(status_col, "")).strip() if status_col else "",
                            "Issues_Found": str(r.get(issues_col, "")).strip() if issues_col else "",
                            "Issue_Details": str(r.get(issues_col, "")).strip() if issues_col else "",
                        }

        # Requested columns (kept exactly; fixed the broken newline in Total_Tax_Calculated)
        columns = [
            "Invoice_ID",
            "Invoice_Number",
            "Invoice_Date",
            "Invoice_Entry_Date",
            "Vendor_Name",
            "Amount",
            "Invoice_Creator_Name",
            "Location",
            "Invoice currency",
            "Method_of_Payment",
            "Account_Head",
            "Validation_Status",
            "Issues_Found",
            "Issue_Details",
            "GST_Number",
            "Row_Index",
            "Validation_Date",
            "Invoice_Currency",
            "Location",  # (duplicate name requested)
            "Tax_Type",
            "Due_Date",
            "Due_Date_Notification",
            "Total_Tax_Calculated",
            "CGST_Amount",
            "SGST_Amount",
            "IGST_Amount",
            "VAT_Amount",
            "TDS_Status",
            "RMS_Invoice_ID",
            "SCID",
        ]

        # Prepare output rows (construct list of values per row, in exact order)
        out_rows: List[List[Optional[str]]] = []
        df_rms = df_rms.fillna("")
        for idx, r in df_rms.iterrows():
            row = r.to_dict()

            invoice_no = self._safe_get(row, ["PurchaseInvNo", "Invoice Number", "Invoice_No", "InvoiceNumber", "VoucherNo"]) or ""
            vendor = self._safe_get(row, ["PartyName", "Vendor Name", "Vendor_Name"]) or ""
            inv_date = self._safe_get(row, ["PurchaseInvDate", "Invoice Date", "Voucherdate"]) or ""
            entry_date = self._safe_get(row, ["Voucherdate", "Invoice_Entry_Date"]) or inv_date
            amount = self._safe_get(row, ["Total", "Amount", "PaytyAmt", "TaxableValue"]) or ""
            creator = self._safe_get(row, ["Inv Created By", "Creator", "Invoice_Creator_Name"]) or "Unknown"
            location = self._safe_get(row, ["State", "Location"]) or ""
            currency = self._safe_get(row, ["Currency", "Invoice currency", "Invoice_Currency"]) or ""
            method = self._safe_get(row, ["Method_of_Payment", "Payment Method"]) or ""
            account_head = self._safe_get(row, ["PurchaseLEDGER", "Account_Head", "Narration"]) or ""
            gst = self._safe_get(row, ["GSTNO", "GST_Number", "GSTIN"]) or ""
            rms_id = self._safe_get(row, ["InvID", "RMS_Invoice_ID"]) or ""
            scid = self._safe_get(row, ["SCID"]) or ""
            due_date = self._safe_get(row, ["Due_Date", "Due Date"]) or ""
            due_note = self._safe_get(row, ["Due_Date_Notification"]) or ""

            cgst = self._num(self._safe_get(row, ["CGSTInputAmt", "CGST_Amount"]) or 0)
            sgst = self._num(self._safe_get(row, ["SGSTInputAmt", "SGST_Amount"]) or 0)
            igst = self._num(self._safe_get(row, ["IGST/VATInputAmt", "IGST_Amount", "IGSTInputAmt"]) or 0)
            vat = self._num(self._safe_get(row, ["VAT", "VAT_Amount"]) or 0)
            total_tax = cgst + sgst + igst + vat

            if igst > 0:
                tax_type = "IGST"
            elif (cgst + sgst) > 0:
                tax_type = "GST"
            elif vat > 0:
                tax_type = "VAT"
            else:
                tax_type = ""

            tds_raw = self._safe_get(row, ["TDS", "TDS_Status"])
            tds_status = "Deducted" if self._num(tds_raw) > 0 else (str(tds_raw) if tds_raw not in (None, "", "0", "0.0") else "Not Deducted")

            # Validation details (from detailed sheet if present)
            v_status = ""
            issues_found = ""
            issue_details = ""
            if invoice_no and invoice_no in validation_lookup:
                got = validation_lookup[invoice_no]
                v_status = got.get("Validation_Status", "") or ""
                issues_found = got.get("Issues_Found", "") or ""
                issue_details = got.get("Issue_Details", "") or ""

            # Build the ordered row (be mindful of duplicate column names)
            values = [
                rms_id,                     # Invoice_ID
                invoice_no,                 # Invoice_Number
                inv_date,                   # Invoice_Date
                entry_date,                 # Invoice_Entry_Date
                vendor,                     # Vendor_Name
                amount,                     # Amount
                creator,                    # Invoice_Creator_Name
                location,                   # Location
                currency,                   # Invoice currency
                method,                     # Method_of_Payment
                account_head,               # Account_Head
                v_status,                   # Validation_Status
                issues_found,               # Issues_Found
                issue_details,              # Issue_Details
                gst,                        # GST_Number
                idx,                        # Row_Index
                datetime.now().strftime("%Y-%m-%d"),  # Validation_Date
                currency,                   # Invoice_Currency
                location,                   # Location (duplicate requested)
                tax_type,                   # Tax_Type
                due_date,                   # Due_Date
                due_note,                   # Due_Date_Notification
                total_tax,                  # Total_Tax_Calculated
                cgst,                       # CGST_Amount
                sgst,                       # SGST_Amount
                igst,                       # IGST_Amount
                vat,                        # VAT_Amount
                tds_status,                 # TDS_Status
                rms_id,                     # RMS_Invoice_ID
                scid,                       # SCID
            ]
            out_rows.append(values)

        out_df = pd.DataFrame(out_rows, columns=columns)

        # Save
        out_path = Path("data") / f"validation_report_formatted_{datetime.now().strftime('%Y-%m-%d')}.xlsx"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            with pd.ExcelWriter(out_path, engine="xlsxwriter") as writer:
                out_df.to_excel(writer, index=False, sheet_name="Validation Report")
            self.logger.info(f"Formatted validation report written: {out_path}")
            return str(out_path)
        except Exception as e:
            self.logger.error(f"Failed to write formatted validation report: {e}")
            return None

    # ---------- ZIP assembly (reports + real invoices) ----------

    def _add_file_if_fits(self, zipf: zipfile.ZipFile, path: str, arcname: str, running_size: int) -> int:
        """Add file to zip if it doesn't push total over max_zip_bytes; return new size (or unchanged if skipped)."""
        try:
            sz = os.path.getsize(path)
        except OSError:
            return running_size
        if running_size + sz > self.max_zip_bytes:
            self.logger.warning(f"Skipping (limit): {path} ({sz} bytes)")
            return running_size
        zipf.write(path, arcname=arcname)
        return running_size + sz

    def _add_invoices_from_inner_zip(self, outer: zipfile.ZipFile, inner_zip_path: str, running_size: int) -> int:
        """Open invoices.zip and copy its contents (pdf/jpg/png) into the outer ZIP until size cap is reached."""
        try:
            with zipfile.ZipFile(inner_zip_path, "r") as inner:
                # Iterate deterministically
                for info in sorted(inner.infolist(), key=lambda i: i.filename):
                    if info.is_dir():
                        continue
                    fname = info.filename
                    ext = os.path.splitext(fname)[1].lower()
                    if ext not in (".pdf", ".png", ".jpg", ".jpeg"):
                        continue
                    fsize = info.file_size or 0
                    if running_size + fsize > self.max_zip_bytes:
                        self.logger.warning(f"Skipping invoice (limit): {fname} ({fsize} bytes)")
                        break
                    data = inner.read(info.filename)
                    outer.writestr(f"invoices/{os.path.basename(fname)}", data)
                    running_size += len(data)
        except Exception as e:
            self.logger.warning(f"Could not extract invoices from {inner_zip_path}: {e}")
        return running_size

    def create_invoice_zip(self) -> Optional[str]:
        """
        Create ZIP that includes:
          - The formatted validation report (this function builds it if missing)
          - Other relevant run reports under data/
          - REAL invoice files from the downloaded invoices.zip (as many as fit)
        """
        # Ensure new formatted report exists
        self.build_formatted_validation_report()

        zip_filename: Optional[str] = None
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            zip_filename = f"invoice_validation_{timestamp}.zip"

            # Collect candidate artifact reports
            candidates: List[str] = []
            candidates += glob.glob("invoice_validation_report_*.xlsx")          # legacy report
            candidates += glob.glob("data/validation_report_formatted_*.xlsx")   # new requested format
            candidates += glob.glob("data/invoice_validation_detailed_*.xlsx")
            candidates += glob.glob("data/*/validation_result.xlsx")
            candidates += glob.glob("data/delta_report_*.xlsx")
            candidates += glob.glob("data/email_summary_*.html")

            # Find the most recent invoices.zip produced by the scraper
            invoice_zips = glob.glob("data/*/invoices.zip") + glob.glob("invoices.zip")
            newest_invoices_zip = max(invoice_zips, key=os.path.getctime) if invoice_zips else None

            running_size = 0
            with zipfile.ZipFile(zip_filename, "w", zipfile.ZIP_DEFLATED) as zipf:
                # Add reports under reports/
                for path in sorted(set(candidates)):
                    if not os.path.isfile(path):
                        continue
                    base = os.path.basename(path)
                    arc = f"reports/{base}"
                    before = running_size
                    running_size = self._add_file_if_fits(zipf, path, arc, running_size)
                    if running_size != before:
                        self.logger.info(f"Added report: {path} -> {arc}")

                # Add REAL invoices: unpack invoices.zip contents into invoices/
                if newest_invoices_zip and os.path.isfile(newest_invoices_zip):
                    running_size = self._add_invoices_from_inner_zip(zipf, newest_invoices_zip, running_size)
                else:
                    self.logger.warning("No invoices.zip found to include real invoices.")

            # Verify zip
            if os.path.exists(zip_filename) and os.path.getsize(zip_filename) > 0:
                self.logger.info(f"ZIP created successfully: {zip_filename} ({os.path.getsize(zip_filename)} bytes)")
                return zip_filename

            self.logger.error("ZIP file creation failed or file is empty")
            return None

        except Exception as e:
            self.logger.error(f"Error creating ZIP: {e}")
            # Cleanup failed
            if zip_filename and os.path.exists(zip_filename):
                try:
                    os.remove(zip_filename)
                except Exception:
                    pass
            return None

    # ---------- Email sender ----------

    def send_email_with_attachments(self, recipients, subject, html_body, zip_file) -> bool:
        """Send HTML email with the assembled ZIP (or without if not available)."""
        try:
            # Normalize recipients → flat list[str]
            flat: List[str] = []
            if isinstance(recipients, (list, tuple, set)):
                items = list(recipients)
            elif recipients is None:
                items = []
            else:
                items = [recipients]

            for r in items:
                if isinstance(r, (list, tuple, set)):
                    for x in r:
                        flat.extend(self._validate_email_list(str(x)))
                else:
                    flat.extend(self._validate_email_list(str(r)))

            # De-dupe preserving order
            seen = set()
            valid_recipients: List[str] = []
            for e in flat:
                if e not in seen:
                    seen.add(e)
                    valid_recipients.append(e)

            if not valid_recipients:
                self.logger.error("No valid recipients found")
                return False

            if not self.username or not self.password:
                self.logger.error("SMTP credentials not configured")
                return False

            # Ensure HTML body is a string
            if not isinstance(html_body, str):
                try:
                    if isinstance(html_body, (list, tuple)):
                        html_body = "\n".join(str(x) for x in html_body)
                    else:
                        html_body = str(html_body)
                except Exception:
                    html_body = "<p>(No content)</p>"

            from_name = os.getenv("SMTP_FROM_NAME", "").strip()
            pretty_from = formataddr((from_name, self.username)) if from_name else self.username

            msg = MIMEMultipart("mixed")
            msg["From"] = pretty_from
            msg["To"] = ", ".join(valid_recipients)
            msg["Subject"] = str(subject) if subject is not None else "Invoice Validation Report"

            # Attach HTML
            html_part = MIMEText(html_body, "html", "utf-8")
            msg.attach(html_part)

            # Attach ZIP (optional)
            if zip_file and os.path.exists(str(zip_file)):
                try:
                    file_size = os.path.getsize(str(zip_file))
                    if file_size > self.max_zip_bytes:
                        self.logger.warning(f"ZIP file too large ({file_size} bytes), skipping attachment")
                    else:
                        with open(str(zip_file), "rb") as attachment:
                            part = MIMEBase("application", "zip")
                            part.set_payload(attachment.read())
                            encoders.encode_base64(part)
                            part.add_header("Content-Disposition", f'attachment; filename="{os.path.basename(str(zip_file))}"')
                            msg.attach(part)
                            self.logger.info(f"ZIP attachment added: {os.path.basename(str(zip_file))} ({file_size} bytes)")
                except Exception as e:
                    self.logger.error(f"Failed to attach ZIP file: {e}")

            # Send
            try:
                with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                    server.starttls()
                    server.login(self.username, self.password)
                    server.send_message(msg)
                self.logger.info(f"Email sent successfully to: {', '.join(valid_recipients)}")
                return True
            except smtplib.SMTPAuthenticationError:
                self.logger.error("SMTP authentication failed - check credentials")
                return False
            except smtplib.SMTPRecipientsRefused:
                self.logger.error("All recipients were refused by server")
                return False
            except smtplib.SMTPException as e:
                self.logger.error(f"SMTP error occurred: {e}")
                return False

        except Exception as e:
            self.logger.error(f"Error sending email: {e}")
            return False

    def validate_email_config(self) -> List[str]:
        issues: List[str] = []
        if not self.username:
            issues.append("Missing SMTP_USER (or EMAIL_USERNAME) environment variable")
        if not self.password:
            issues.append("Missing SMTP_PASS (or EMAIL_PASSWORD) environment variable")
        if not self.default_recipients:
            issues.append("No valid email recipients configured")
        if not self.smtp_server:
            issues.append("Missing SMTP server configuration")
        return issues


class EmailNotifier:
    """
    Compatibility wrapper around EnhancedEmailSystem so existing code can:
        from email_notifier import EmailNotifier
    and then call: send / send_report / send_validation_email / send_validation_report
    """

    def __init__(
        self,
        smtp_host: Optional[str] = None,
        smtp_port: Optional[int] = None,
        smtp_user: Optional[str] = None,
        smtp_pass: Optional[str] = None,
        use_tls: Optional[bool] = None,  # kept for API symmetry; STARTTLS is used by default
        from_name: Optional[str] = None,
        recipients: Optional[List[str]] = None,
    ):
        host = smtp_host or os.getenv("SMTP_HOST") or os.getenv("SMTP_SERVER", "smtp.office365.com")
        port = int(smtp_port or os.getenv("SMTP_PORT", "587"))
        user = smtp_user or os.getenv("SMTP_USER") or os.getenv("EMAIL_USERNAME")
        pwd = smtp_pass or os.getenv("SMTP_PASS") or os.getenv("EMAIL_PASSWORD")

        self._engine = EnhancedEmailSystem(
            smtp_server=host,
            smtp_port=port,
            username=user,
            password=pwd,
        )
        self._from_name = from_name or os.getenv("SMTP_FROM_NAME", "")

        if recipients:
            # Override/validate provided recipients
            validated: List[str] = []
            src = recipients if isinstance(recipients, list) else [recipients]
            for r in src:
                validated.extend(self._engine._validate_email_list(str(r)))
            if validated:
                self._engine.default_recipients = validated

    def _zip_attachments_if_needed(self, attachments) -> Optional[str]:
        """
        Accepts:
          - None
          - path to a .zip (str/Path)
          - list of file paths (bundled into a temporary .zip)
        Any other type is ignored gracefully.
        """
        if attachments is None:
            return None

        # Single string/path
        if isinstance(attachments, (str, os.PathLike)):
            s = str(attachments)
            if s.lower().endswith(".zip") and os.path.isfile(s):
                return s
            if os.path.isfile(s):
                ts = datetime.now().strftime("%Y%m%d_%H%M%S")
                zip_path = f"email_attachments_{ts}.zip"
                try:
                    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
                        zf.write(s, arcname=os.path.basename(s))
                    return zip_path
                except Exception as e:
                    logging.error(f"EmailNotifier: Failed to bundle single attachment: {e}")
                    try:
                        if os.path.exists(zip_path):
                            os.remove(zip_path)
                    except Exception:
                        pass
                    return None
            logging.warning("EmailNotifier: attachments is a string but not a file path; ignoring.")
            return None

        # List of paths
        if isinstance(attachments, list):
            paths = [str(p) for p in attachments if isinstance(p, (str, os.PathLike))]
            if not paths:
                return None
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            zip_path = f"email_attachments_{ts}.zip"
            try:
                with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
                    for p in paths:
                        if os.path.isfile(p):
                            zf.write(p, arcname=os.path.basename(p))
                return zip_path if os.path.getsize(zip_path) > 0 else None
            except Exception as e:
                logging.error(f"EmailNotifier: Failed to bundle attachments list: {e}")
                try:
                    if os.path.exists(zip_path):
                        os.remove(zip_path)
                except Exception:
                    pass
                return None

        logging.warning(f"EmailNotifier: attachments of unsupported type {type(attachments).__name__}; ignoring.")
        return None

    def send(self, subject: str, html_body, attachments=None, recipients: Optional[List[str]] = None, from_email: Optional[str] = None) -> bool:
        if recipients:
            # Normalize/validate here so engine gets good addresses
            validated: List[str] = []
            src = recipients if isinstance(recipients, list) else [recipients]
            for r in src:
                validated.extend(self._engine._validate_email_list(str(r)))
            if validated:
                self._engine.default_recipients = validated

        # Try to use provided attachments
        zip_file = self._zip_attachments_if_needed(attachments)

        # If none/invalid, build our reports+invoices ZIP
        if not zip_file:
            zip_file = self._engine.create_invoice_zip()

        # If zip exists but exceeds cap, rebuild a smaller one (reports + as many invoices as fit)
        try:
            if zip_file and os.path.getsize(zip_file) > self._engine.max_zip_bytes:
                logging.warning("EmailNotifier: Provided ZIP exceeds size cap; rebuilding under size limit.")
                zip_file = self._engine.create_invoice_zip()
                if zip_file and os.path.getsize(zip_file) > self._engine.max_zip_bytes:
                    logging.warning("EmailNotifier: Could not build a small enough ZIP; sending without attachment.")
                    zip_file = None
        except Exception as _e:
            logging.warning(f"EmailNotifier: size check failed ({_e}); proceeding without attachment.")
            zip_file = None

        return self._engine.send_email_with_attachments(
            self._engine.default_recipients,
            subject,
            html_body,
            zip_file
        )

    # Backward-compatible aliases
    def send_report(self, subject: str, html_body, attachments=None, recipients: Optional[List[str]] = None) -> bool:
        return self.send(subject, html_body, attachments, recipients)

    def send_validation_email(self, subject: str, html_body, attachments=None, recipients: Optional[List[str]] = None) -> bool:
        return self.send(subject, html_body, attachments, recipients)

    def send_validation_report(self, subject: str, html_body, attachments=None, recipients: Optional[List[str]] = None) -> bool:
        return self.send(subject, html_body, attachments, recipients)


# Optional local test
if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        handlers=[logging.StreamHandler(), logging.FileHandler("email_system.log")],
    )

    print("🧪 Testing EnhancedEmailSystem configuration...")
    engine = EnhancedEmailSystem()
    issues = engine.validate_email_config()
    if issues:
        print("⚠️ Config issues:")
        for i in issues:
            print("  -", i)
    else:
        print(f"✅ Config OK. Default recipients: {engine.default_recipients}")
        html = engine.create_professional_html_template(
            {"failed": 1, "warnings": 2, "passed": 3},
            datetime.now() + timedelta(days=3),
        )
        z = engine.create_invoice_zip()
        ok = engine.send_email_with_attachments(engine.default_recipients, "Test Email (attachments)", html, z)
        print("Send result:", ok)
