# email_notifier.py

import os
import re
import glob
import logging
import smtplib
from typing import List, Optional
from datetime import datetime, timedelta
from pathlib import Path
import zipfile

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders

__all__ = ["EnhancedEmailSystem", "EmailNotifier"]


class EnhancedEmailSystem:
    """Enhanced email system with professional HTML templates and robust error handling"""

    def __init__(self, smtp_server=None, smtp_port=None, username=None, password=None):
        # Prefer SMTP_* secrets; fallback to EMAIL_*
        self.smtp_server = smtp_server or os.getenv("SMTP_HOST") or os.getenv("SMTP_SERVER", "smtp.office365.com")
        self.smtp_port = int(smtp_port or os.getenv("SMTP_PORT", "587"))
        self.username = username or os.getenv("SMTP_USER") or os.getenv("EMAIL_USERNAME")
        self.password = password or os.getenv("SMTP_PASS") or os.getenv("EMAIL_PASSWORD")

        # Recipients configuration with validation
        recipients_str = (
            os.getenv("AP_TEAM_EMAIL_LIST")
            or os.getenv("EMAIL_RECIPIENTS")
            or os.getenv("TEAM_EMAIL_LIST")
            or ""
        )
        self.default_recipients = self._validate_email_list(recipients_str) if recipients_str else []

        # Logger
        self.logger = logging.getLogger(__name__)

    def _validate_email_list(self, recipients_str: str) -> List[str]:
        """Validate and clean email recipient list (comma/semicolon separated)"""
        email_pattern = re.compile(r"^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$")
        emails: List[str] = []
        for raw in recipients_str.replace(";", ",").split(","):
            email = raw.strip()
            if not email:
                continue
            if email_pattern.match(email):
                emails.append(email)
            else:
                self.logger.warning(f"Invalid email format ignored: {email}")
        return emails

    def create_professional_html_template(self, validation_data: dict, deadline_date: datetime) -> str:
        """Create professional HTML email template with enhanced formatting"""
        critical_count = validation_data.get("failed", 0)
        warning_count = validation_data.get("warnings", 0)
        passed_count = validation_data.get("passed", 0)
        total_count = critical_count + warning_count + passed_count
        pass_rate = (passed_count / total_count * 100) if total_count > 0 else 0

        critical_amount = "₹1,50,000"
        warning_amount = "₹1,40,000"

        html_template = f"""
<!DOCTYPE html>
<html>
  <body style="font-family: Arial, sans-serif; color:#111;">
    <h2>🏢 KOENIG INVOICE VALIDATION REPORT</h2>
    <p>Automated Processing Summary - {datetime.now().strftime('%B %d, %Y')}</p>

    <h3>📊 EXECUTIVE SUMMARY</h3>
    <p>Processing Rate: <b>{pass_rate:.1f}%</b> ({passed_count}/{total_count} invoices processed successfully)</p>

    <table border="1" cellpadding="6" cellspacing="0">
      <tr><th>Status</th><th>Count</th><th>Financial Impact</th></tr>
      <tr><td>🚨 CRITICAL ISSUES</td><td>{critical_count}</td><td>{critical_amount}</td></tr>
      <tr><td>⚠️ WARNING ITEMS</td><td>{warning_count}</td><td>{warning_amount}</td></tr>
      <tr><td>✅ SUCCESSFULLY PROCESSED</td><td>{passed_count}</td><td>Ready for Payment</td></tr>
    </table>

    <h3>🚨 IMMEDIATE ACTION REQUIRED</h3>
    <p>Response Deadline: <b>{deadline_date.strftime('%B %d, %Y at %I:%M %p IST')}</b></p>
    <p>Non-response will trigger automatic escalation to Finance Head</p>

    <h3>🎯 REQUIRED ACTIONS</h3>
    <ul>
      <li>Review Failed Invoices: see attached Excel report for detailed validation errors</li>
      <li>Provide Corrections or Exceptions</li>
      <li>Vendor Master Updates if needed</li>
      <li>Confirm approval status for pending invoices</li>
      <li>Attach supporting documents for flagged transactions</li>
    </ul>

    <h3>📎 ATTACHMENTS INCLUDED</h3>
    <ul>
      <li>Excel Validation Report</li>
      <li>Invoice Files ZIP</li>
      <li>Processing Summary</li>
    </ul>

    <h3>📞 FOR QUESTIONS OR SUPPORT</h3>
    <table>
      <tr><td>Finance Team:</td><td>Accounts@koenig-solutions.com</td></tr>
      <tr><td>System Support:</td><td>tax@koenig-solutions.com</td></tr>
    </table>

    <hr/>
    <p>Koenig Solutions Pvt. Ltd. | Generated by Invoice Management System</p>
    <p style="color:#555;">This is an automated report containing confidential information</p>
  </body>
</html>
        """.strip()

        return html_template

    def create_invoice_zip(self, invoice_files=None, validation_period: Optional[str] = None) -> Optional[str]:
        """Create ZIP file with invoice copies and Excel report"""
        zip_filename: Optional[str] = None
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            period = validation_period or "current"
            zip_filename = f"invoice_validation_{timestamp}.zip"

            with zipfile.ZipFile(zip_filename, "w", zipfile.ZIP_DEFLATED) as zipf:
                # Add latest Excel validation report
                excel_files = glob.glob("invoice_validation_report_*.xlsx")
                if excel_files:
                    latest_excel = max(excel_files, key=os.path.getctime)
                    if os.path.exists(latest_excel):
                        zipf.write(latest_excel, "validation_report.xlsx")
                        self.logger.info(f"Added Excel report to ZIP: {latest_excel}")
                    else:
                        self.logger.warning(f"Excel file not found: {latest_excel}")

                # Add invoice files
                invoice_count = 0
                invoice_dir = Path("invoice_files")
                if invoice_dir.exists():
                    for file_path in invoice_dir.rglob("*"):
                        if file_path.is_file() and file_path.suffix.lower() in [".pdf", ".png", ".jpg", ".jpeg"]:
                            try:
                                zipf.write(str(file_path), f"invoice_files/{file_path.name}")
                                invoice_count += 1
                            except Exception as e:
                                self.logger.warning(f"Failed to add file {file_path}: {e}")

                # Verify
                if os.path.exists(zip_filename) and os.path.getsize(zip_filename) > 0:
                    self.logger.info(f"ZIP created successfully: {zip_filename} ({invoice_count} invoice files)")
                    return zip_filename
                self.logger.error("ZIP file creation failed or file is empty")
                return None

        except Exception as e:
            self.logger.error(f"Error creating ZIP: {e}")
            # Cleanup failed
            if zip_filename and os.path.exists(zip_filename):
                try:
                    os.remove(zip_filename)
                except Exception:
                    pass
            return None

    def send_email_with_attachments(self, recipients, subject, html_body, zip_file) -> bool:
        """Send professional HTML email with ZIP attachment - Enhanced error handling"""
        try:
            # Normalize recipients → flat list[str]
            flat: List[str] = []
            if isinstance(recipients, (list, tuple, set)):
                items = list(recipients)
            elif recipients is None:
                items = []
            else:
                items = [recipients]

            for r in items:
                if isinstance(r, (list, tuple, set)):
                    for x in r:
                        flat.extend(self._validate_email_list(str(x)))
                else:
                    flat.extend(self._validate_email_list(str(r)))

            # De-dupe preserving order
            seen = set()
            valid_recipients: List[str] = []
            for e in flat:
                if e not in seen:
                    seen.add(e)
                    valid_recipients.append(e)

            if not valid_recipients:
                self.logger.error("No valid recipients found")
                return False

            if not self.username or not self.password:
                self.logger.error("SMTP credentials not configured")
                return False

            # Ensure HTML body is a string
            if not isinstance(html_body, str):
                try:
                    if isinstance(html_body, (list, tuple)):
                        html_body = "\n".join(str(x) for x in html_body)
                    else:
                        html_body = str(html_body)
                except Exception:
                    html_body = "<p>(No content)</p>"

            msg = MIMEMultipart("mixed")
            msg["From"] = self.username
            msg["To"] = ", ".join(valid_recipients)
            msg["Subject"] = str(subject) if subject is not None else "Invoice Validation Report"

            # Attach HTML
            html_part = MIMEText(html_body, "html", "utf-8")
            msg.attach(html_part)

            # Attach ZIP (optional)
            if zip_file and os.path.exists(str(zip_file)):
                try:
                    file_size = os.path.getsize(str(zip_file))
                    if file_size > 25 * 1024 * 1024:
                        self.logger.warning(f"ZIP file too large ({file_size} bytes), skipping attachment")
                    else:
                        with open(str(zip_file), "rb") as attachment:
                            part = MIMEBase("application", "zip")
                            part.set_payload(attachment.read())
                            encoders.encode_base64(part)
                            part.add_header("Content-Disposition", f'attachment; filename="{os.path.basename(str(zip_file))}"')
                            msg.attach(part)
                            self.logger.info(f"ZIP attachment added: {os.path.basename(str(zip_file))} ({file_size} bytes)")
                except Exception as e:
                    self.logger.error(f"Failed to attach ZIP file: {e}")

            # Send
            try:
                with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                    server.starttls()
                    server.login(self.username, self.password)
                    server.send_message(msg)
                self.logger.info(f"Email sent successfully to: {', '.join(valid_recipients)}")
                return True
            except smtplib.SMTPAuthenticationError:
                self.logger.error("SMTP authentication failed - check credentials")
                return False
            except smtplib.SMTPRecipientsRefused:
                self.logger.error("All recipients were refused by server")
                return False
            except smtplib.SMTPException as e:
                self.logger.error(f"SMTP error occurred: {e}")
                return False

        except Exception as e:
            self.logger.error(f"Error sending email: {e}")
            return False
        finally:
            # No-op: let the caller decide whether to delete temporary zips
            pass

    def validate_email_config(self) -> List[str]:
        """Validate email configuration before sending"""
        issues: List[str] = []
        if not self.username:
            issues.append("Missing SMTP_USER (or EMAIL_USERNAME) environment variable")
        if not self.password:
            issues.append("Missing SMTP_PASS (or EMAIL_PASSWORD) environment variable")
        if not self.default_recipients:
            issues.append("No valid email recipients configured")
        if not self.smtp_server:
            issues.append("Missing SMTP server configuration")
        return issues


class EmailNotifier:
    """
    Compatibility wrapper around EnhancedEmailSystem so code can:
        from email_notifier import EmailNotifier
    and then call: send / send_report / send_validation_email / send_validation_report
    """

    def __init__(
        self,
        smtp_host: Optional[str] = None,
        smtp_port: Optional[int] = None,
        smtp_user: Optional[str] = None,
        smtp_pass: Optional[str] = None,
        use_tls: Optional[bool] = None,  # kept for API symmetry; STARTTLS is used by default
        from_name: Optional[str] = None,
        recipients: Optional[List[str]] = None,
    ):
        host = smtp_host or os.getenv("SMTP_HOST") or os.getenv("SMTP_SERVER", "smtp.office365.com")
        port = int(smtp_port or os.getenv("SMTP_PORT", "587"))
        user = smtp_user or os.getenv("SMTP_USER") or os.getenv("EMAIL_USERNAME")
        pwd = smtp_pass or os.getenv("SMTP_PASS") or os.getenv("EMAIL_PASSWORD")

        self._engine = EnhancedEmailSystem(
            smtp_server=host,
            smtp_port=port,
            username=user,
            password=pwd,
        )
        self._from_name = from_name or os.getenv("SMTP_FROM_NAME", "")

        if recipients:
            # Override/validate provided recipients
            validated: List[str] = []
            src = recipients if isinstance(recipients, list) else [recipients]
            for r in src:
                validated.extend(self._engine._validate_email_list(str(r)))
            if validated:
                self._engine.default_recipients = validated

    def _zip_attachments_if_needed(self, attachments) -> Optional[str]:
        """
        Accepts:
          - None
          - path to a .zip (str/Path)
          - list of file paths (bundled into a temporary .zip)
        Any other type is ignored gracefully.
        """
        if attachments is None:
            return None

        # Single string/path
        if isinstance(attachments, (str, os.PathLike)):
            s = str(attachments)
            if s.lower().endswith(".zip") and os.path.isfile(s):
                return s
            if os.path.isfile(s):
                ts = datetime.now().strftime("%Y%m%d_%H%M%S")
                zip_path = f"email_attachments_{ts}.zip"
                try:
                    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
                        zf.write(s, arcname=os.path.basename(s))
                    return zip_path
                except Exception as e:
                    logging.error(f"EmailNotifier: Failed to bundle single attachment: {e}")
                    try:
                        if os.path.exists(zip_path):
                            os.remove(zip_path)
                    except Exception:
                        pass
                    return None
            logging.warning("EmailNotifier: attachments is a string but not a file path; ignoring.")
            return None

        # List of paths
        if isinstance(attachments, list):
            paths = [str(p) for p in attachments if isinstance(p, (str, os.PathLike))]
            if not paths:
                return None
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            zip_path = f"email_attachments_{ts}.zip"
            try:
                with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
                    for p in paths:
                        if os.path.isfile(p):
                            zf.write(p, arcname=os.path.basename(p))
                return zip_path if os.path.getsize(zip_path) > 0 else None
            except Exception as e:
                logging.error(f"EmailNotifier: Failed to bundle attachments list: {e}")
                try:
                    if os.path.exists(zip_path):
                        os.remove(zip_path)
                except Exception:
                    pass
                return None

        logging.warning(f"EmailNotifier: attachments of unsupported type {type(attachments).__name__}; ignoring.")
        return None

    def send(self, subject: str, html_body, attachments=None, recipients: Optional[List[str]] = None, from_email: Optional[str] = None) -> bool:
        if recipients:
            # Normalize/validate here so engine gets good addresses
            validated: List[str] = []
            src = recipients if isinstance(recipients, list) else [recipients]
            for r in src:
                validated.extend(self._engine._validate_email_list(str(r)))
            if validated:
                self._engine.default_recipients = validated

        zip_file = self._zip_attachments_if_needed(attachments)
        return self._engine.send_email_with_attachments(
            self._engine.default_recipients,
            subject,
            html_body,
            zip_file
        )

    # Backward-compatible aliases
    def send_report(self, subject: str, html_body, attachments=None, recipients: Optional[List[str]] = None) -> bool:
        return self.send(subject, html_body, attachments, recipients)

    def send_validation_email(self, subject: str, html_body, attachments=None, recipients: Optional[List[str]] = None) -> bool:
        return self.send(subject, html_body, attachments, recipients)

    def send_validation_report(self, subject: str, html_body, attachments=None, recipients: Optional[List[str]] = None) -> bool:
        return self.send(subject, html_body, attachments, recipients)


# Optional local test
if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        handlers=[logging.StreamHandler(), logging.FileHandler("email_system.log")],
    )

    print("🧪 Testing EnhancedEmailSystem configuration...")
    engine = EnhancedEmailSystem()
    issues = engine.validate_email_config()
    if issues:
        print("⚠️ Config issues:")
        for i in issues:
            print("  -", i)
    else:
        print(f"✅ Config OK. Default recipients: {engine.default_recipients}")
        # Build a tiny HTML and try without attachments (dry test envs may block SMTP login)
        html = engine.create_professional_html_template(
            {"failed": 1, "warnings": 2, "passed": 3},
            datetime.now() + timedelta(days=3),
        )
        ok = engine.send_email_with_attachments(engine.default_recipients, "Test Email (no attachment)", html, None)
        print("Send result:", ok)
