name: Vendor Invoice Validator

on:
  schedule:
    - cron: '0 12 */4 * *'
  workflow_dispatch:

jobs:
  run-validator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run RMS Scraper
        run: python main.py

      - name: Compare Invoices
        run: python compare_invoices.py

      - name: Email Delta Report
        env:
          OUTLOOK_APP_PASSWORD: ${{ secrets.OUTLOOK_APP_PASSWORD }}
        run: python email_report.py
