name: Vendor Invoice Validator Cron

on:
  schedule:
    - cron: "0 5 */4 * *"  # Every 4 days at 5:00 AM UTC (10:30 AM IST)
  workflow_dispatch:       # Manual trigger

jobs:
  run-validator:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Invoice Validator
        run: python run_validator.py

      - name: 📧 Email Report
        run: python email_report.py
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}

